from django.urls import path

from . import views

urlpatterns = [
    path("consultancy/", views.consultancy_hub, name="consultancy_hub"),
    path("unlock/", views.unlock_access, name="unlock_access"),
    path("exit/", views.exit_access, name="exit_access"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("tracker/", views.report_tracker, name="report_tracker"),
    path("sharepoint-tracker/", views.sharepoint_tracker, name="sharepoint_tracker"),
    path("sharepoint-tracker/<int:pk>/edit/", views.edit_sharepoint_entry, name="edit_sharepoint_entry"),
    path("sharepoint-tracker/<int:pk>/delete/", views.delete_sharepoint_entry, name="delete_sharepoint_entry"),
    path("operations/", views.operations_staff_view, name="operations_staff"),
    path("reports/<int:pk>/edit/", views.edit_report, name="report_edit"),
    path("dashboards/alternative-investments/", views.alt_investments_dashboard, name="alt_investments_dashboard"),
    path("dashboards/alternative-investments/unlock/", views.alt_investments_unlock, name="alt_investments_unlock"),
    path("dashboards/alternative-investments/exit/", views.alt_investments_exit, name="alt_investments_exit"),
    path("dashboards/alternative-investments/reviews/", views.alt_investments_reviews, name="alt_investments_reviews"),
    path("dashboards/alternative-investments/add/", views.alt_investment_add, name="alt_investment_add"),
    path("dashboards/alternative-investments/<int:pk>/", views.alt_investment_detail, name="alt_investment_detail"),
    path("dashboards/alternative-investments/<int:pk>/edit/", views.alt_investment_edit, name="alt_investment_edit"),
    path("dashboards/alternative-investments/<int:pk>/delete/", views.alt_investment_delete, name="alt_investment_delete"),
    path("dashboards/business-development/", views.business_development_dashboard, name="business_development_dashboard"),
    path("dashboards/business-development/unlock/", views.business_development_unlock, name="business_development_unlock"),
    path("dashboards/business-development/exit/", views.business_development_exit, name="business_development_exit"),
    path("dashboards/business-development/ips-reviews/", views.ips_reviews_list, name="ips_reviews_list"),
    path("dashboards/business-development/tenders/", views.tenders_list, name="tenders_list"),
    path("dashboards/business-development/self-generated/", views.self_generated_list, name="self_generated_list"),
    path("dashboards/business-development/ips-reviews/add/", views.ips_review_add, name="ips_review_add"),
    path("dashboards/business-development/ips-reviews/<int:pk>/edit/", views.ips_review_edit, name="ips_review_edit"),
    path("dashboards/business-development/ips-reviews/<int:pk>/delete/", views.ips_review_delete, name="ips_review_delete"),
    path("dashboards/business-development/tenders/add/", views.tender_add, name="tender_add"),
    path("dashboards/business-development/tenders/<int:pk>/edit/", views.tender_edit, name="tender_edit"),
    path("dashboards/business-development/tenders/<int:pk>/delete/", views.tender_delete, name="tender_delete"),
    path("dashboards/business-development/self-generated/add/", views.target_add, name="target_add"),
    path("dashboards/business-development/self-generated/<int:pk>/edit/", views.target_edit, name="target_edit"),
    path("dashboards/business-development/self-generated/<int:pk>/delete/", views.target_delete, name="target_delete"),
    path("dashboards/hr-action-items/", views.hr_action_items_dashboard, name="hr_action_items_dashboard"),
]
