# Generated by Django 5.2.4 on 2026-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('crm_name', models.CharField(max_length=120)),
                ('operations_assignee', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status_phase', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('sent_to_client', 'Sent to Client')], default='pending', max_length=20)),
                ('submitted_tick', models.BooleanField(default=False)),
                ('reviewed_tick', models.BooleanField(default=False)),
                ('sent_to_client_tick', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['operations_assignee', 'crm_name', 'client_name'],
            },
        ),
    ]
