# Generated by Django 5.2.4 on 2026-05-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_crmactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('crm_owner', models.CharField(max_length=120)),
                ('action_item_text', models.TextField()),
                ('progress_update', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Work in Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cleared', 'Cleared'), ('deleted', 'Deleted'), ('imported', 'Imported')], max_length=20)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='reports.crmactionitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
