# Generated by Django 5.2.13 on 2026-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alternativeinvestmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='status_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='status_headline_color',
            field=models.CharField(choices=[('green', 'Green / On Track'), ('amber', 'Amber / Watch'), ('red', 'Red / Critical')], default='green', max_length=20),
        ),
    ]
