# Generated by Django 5.2.13 on 2026-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alternativeinvestmentitem_status_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='investment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='pension_funds_invested',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='performance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='status_developments',
            field=models.TextField(blank=True),
        ),
    ]
