# Generated by Django 5.2.13 on 2026-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alternativeinvestmentitem_investment_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_count_label', models.CharField(default='15+', max_length=64)),
                ('pension_funds_label', models.CharField(default='48+', max_length=64)),
                ('best_performers', models.PositiveIntegerField(default=0)),
                ('distressed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
            },
        ),
    ]
