# Generated by Django 5.2.13 on 2026-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dashboardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeinvestmentitem',
            name='risk',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
