# Generated by Django 5.2.4 on 2026-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_add_risk_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=255)),
                ('ic_crm', models.CharField(blank=True, max_length=120)),
                ('administrator', models.CharField(blank=True, max_length=255)),
                ('admin_crm', models.CharField(blank=True, max_length=120)),
                ('member_fin_schedules', models.BooleanField(default=False)),
                ('financial_review', models.BooleanField(default=False)),
                ('replacement_ratios', models.CharField(blank=True, max_length=255)),
                ('date_data_received', models.DateField(blank=True, null=True)),
                ('date_sent_to_client', models.DateField(blank=True, null=True)),
                ('workshop_required', models.BooleanField(default=False)),
                ('asset_mgr_mandates', models.CharField(blank=True, max_length=255)),
                ('status_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fund_name'],
            },
        ),
        migrations.CreateModel(
            name='SelfGeneratedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('administrator', models.CharField(blank=True, max_length=255)),
                ('business_target', models.CharField(blank=True, max_length=255)),
                ('fund_size_usd_m', models.CharField(blank=True, max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='TenderReferralEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('status_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
    ]
