# Generated by Django 5.2.13 on 2026-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_ipsreviewentry_selfgeneratedtarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfgeneratedtarget',
            name='source_section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenderreferralentry',
            name='source_section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
