# Generated by Django 5.2.14 on 2026-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_selfgeneratedtarget_source_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePointTrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('crm_name', models.CharField(blank=True, max_length=120)),
                ('alternate_name', models.CharField(blank=True, max_length=120)),
                ('word_submitted', models.BooleanField(default=False)),
                ('excel_submitted', models.BooleanField(default=False)),
                ('pdf_submitted', models.BooleanField(default=False)),
                ('due_date', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted_word', 'Submitted Word'), ('submitted_word_and_excel', 'Submitted Word and Excel'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
    ]
