# Generated by Django 5.2.14 on 2026-07-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_sharepointtrackerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepointtrackerentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted_word', 'Submitted Word'), ('submitted_pdf', 'Submitted PDF'), ('submitted_excel', 'Submitted Excel'), ('submitted_word_and_excel', 'Submitted Word and Excel'), ('submitted_word_and_pdf', 'Submitted Word and PDF'), ('submitted_excel_and_pdf', 'Submitted Excel and PDF'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('proposal_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('preliminary', 'Preliminary analysis done'), ('under_review', 'Under review'), ('finalised', 'Finalised'), ('approved', 'Approved'), ('declined', 'Declined')], default='received', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'proposal_name'],
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_documents/%Y/%m/%d/')),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reports.proposal')),
            ],
            options={
                'ordering': ['document_name', 'uploaded_at'],
            },
        ),
    ]
